[package]
name = "phi3-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.89"
candle-core = "0.7.0"
candle-nn = "0.7.0"
candle-transformers = "0.7.0"
hf-hub = "0.3.2"
serde = "1.0.210"
serde_json = "1.0.128"
tokenizers = "0.20.0"
